### ISSUE TITLE
missing download file in oak-occurrences use case?

### ISSUE THREAD

**Issue by cboettig** [sckott/msrgbif#8]
This line fails for me, I don't see the file it is trying to download:

https://github.com/sckott/gbifms/blame/gh-pages/use-cases/oak-occurrences.Rmd#L36

**Comment by sckott** [comment]
thanks, will fix

**Comment by sckott** [comment]
may need to change the use case as that file is no longer avail.

**Comment by sckott** [comment]
fixed, reworked to use a diff. taxon, diff data source
