### ISSUE TITLE
Circle errors

### ISSUE THREAD

**Issue by cboettig** [sckott/msrgbif#9]
Looks like the current circle error is due to to the fact that `littler` loads so few packages.  You could add `methods`, `stats`, `graphics`, and `grDevices` to the library calls in the `niche-modelling`, but I find it easier to omit these and run with:

```
R -e 'rmarkdown::render("manuscript.Rmd")'
```

That way you get all the packages a usual R session has (unlike `r` or `RScript`).  

It also looks like you will then need to install the most recent `wicket` version from GitHub to resolve another error.  

That should get you up to the issue at #8.

HTH

**Comment by cboettig** [comment]
p.s.  since `rocker/ropensci` is such a big image, I'd consider switching to `rocker/geospatial:3.4.1` (using the vesion tag for reproducibility) , and add a DESCRIPTION file to this repo like so:  

```
Package: compendium
Version: 0.1.0
Depends: rmarkdown, tidyverse, rgbif, dismo
Remotes: ropensci/wicket@99d3b14
```

Then I'd have circle-ci run:

```
run -ti -v $(pwd):/data -w /data rocker/geospatial:3.4.1 R -e 'devtools::install(); rmarkdown::render("manuscript.Rmd")'
```

**Comment by sckott** [comment]
made the changes, still getting a wicket error though, not sure why

**Comment by sckott** [comment]
got a successful run https://circleci.com/gh/sckott/gbifms/58 

now trying to get deploy working

**Comment by sckott** [comment]
working now except deploy is not working, meh, im over it, can't get it to work, can just manually update pdf in repo i guess

**Comment by cboettig** [comment]
yeah, I usually do that anyway so I don't like having to copy my credentials around. (I do wish GitHub would issue repo-specific PATs instead of global PATs!)  Good that it builds on circle, that's always nice for reproducibility!  

Anyway, I think this is good to go as a preprint now, yes?

**Comment by sckott** [comment]
i think so, okay if i submit?

(for deploy, i'll see if can get a deploy to S3 at least, so we have a stable URL to link to)

**Comment by cboettig** [comment]
yup, submit away! 🚀 

For stable URL, let's just activate the Zenodo toggle and tag a `preprint` release.  Of course that gives us only a DOI for the repo as a whole, but anyone just wanting the pdf file should probably use the DOI that goes to the preprint anyway.

**Comment by sckott** [comment]
Right, makes sense  on Zenodo front, will do

**Comment by sckott** [comment]
<img width="445" alt="screen shot 2017-09-26 at 11 51 18 am" src="https://user-images.githubusercontent.com/577668/30878228-0c123d80-a2b1-11e7-8f1b-99b22c06a1a7.png">

thoughts @cboettig ?

**Comment by sckott** [comment]
computer sci i guess?

**Comment by cboettig** [comment]
I would go with Life Sci, since I think that's more the 'audience' of the piece.
